In [1]:
import pandas as pd

df = pd.read_csv("hospital_readmissions.csv")  # change name if needed
df.head()

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Missing,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Missing,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Missing,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                25000 non-null  object
 1   time_in_hospital   25000 non-null  int64
 2   n_lab_procedures   25000 non-null  int64
 3   n_procedures       25000 non-null  int64
 4   n_medications      25000 non-null  int64
 5   n_outpatient       25000 non-null  int64
 6   n_inpatient        25000 non-null  int64
 7   n_emergency        25000 non-null  int64
 8   medical_specialty  25000 non-null  object
 9   diag_1             25000 non-null  object
 10  diag_2             25000 non-null  object
 11  diag_3             25000 non-null  object
 12  glucose_test       25000 non-null  object
 13  A1Ctest            25000 non-null  object
 14  change             25000 non-null  object
 15  diabetes_med       25000 non-null  object
 16  readmitted         25000 non-null  object
dtypes: int64(7), object(10)
memory usage: 3.2+ MB

In [3]:
df.describe()

,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency
count,25000.00000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000
mean,4.45332,43.24076,1.352360,16.252400,0.366400,0.615960,0.186600
std,3.00147,19.81862,1.715179,8.060532,1.195478,1.177951,0.885873
min,1.00000,1.00000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,2.00000,31.00000,0.000000,11.000000,0.000000,0.000000,0.000000
50%,4.00000,44.00000,1.000000,15.000000,0.000000,0.000000,0.000000
75%,6.00000,57.00000,2.000000,20.000000,0.000000,1.000000,0.000000
max,14.00000,113.00000,6.000000,79.000000,33.000000,15.000000,64.000000

In [4]:
df.describe(include="all")

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
count,25000,25000.00000,25000.00000,25000.000000,25000.000000,25000.000000,25000.000000,25000.000000,25000,25000,25000,25000,25000,25000,25000,25000,25000
unique,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,8,8,8,3,3,2,2,2
top,[70-80),NaN,NaN,NaN,NaN,NaN,NaN,NaN,Missing,Circulatory,Other,Other,no,no,no,yes,no
freq,6837,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12382,7824,9056,9107,23625,20938,13497,19228,13246
mean,NaN,4.45332,43.24076,1.352360,16.252400,0.366400,0.615960,0.186600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,3.00147,19.81862,1.715179,8.060532,1.195478,1.177951,0.885873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,1.00000,1.00000,0.000000,1.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,2.00000,31.00000,0.000000,11.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,4.00000,44.00000,1.000000,15.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,6.00000,57.00000,2.000000,20.000000,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,14.00000,113.00000,6.000000,79.000000,33.000000,15.000000,64.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.isnull().sum()

age                  0
time_in_hospital     0
n_lab_procedures     0
n_procedures         0
n_medications        0
n_outpatient         0
n_inpatient          0
n_emergency          0
medical_specialty    0
diag_1               0
diag_2               0
diag_3               0
glucose_test         0
A1Ctest              0
change               0
diabetes_med         0
readmitted           0
dtype: int64

In [6]:
df.shape

(25000, 17)

In [7]:
df.columns

Index(['age', 'time_in_hospital', 'n_lab_procedures', 'n_procedures',
       'n_medications', 'n_outpatient', 'n_inpatient', 'n_emergency',
       'medical_specialty', 'diag_1', 'diag_2', 'diag_3', 'glucose_test',
       'A1Ctest', 'change', 'diabetes_med', 'readmitted'],
      dtype='object')

In [8]:
df['readmitted'].value_counts()

readmitted
no     13246
yes    11754
Name: count, dtype: int64

In [9]:
df.groupby('readmitted')['time_in_hospital'].mean()

readmitted
no     4.331345
yes    4.590778
Name: time_in_hospital, dtype: float64

In [10]:


categorical_cols = ['age','medical_specialty','glucose_test','A1Ctest','change','diabetes_med']

for col in categorical_cols:
    print("Column:", col)
    print(pd.crosstab(df[col], df['readmitted'], normalize='index')*100)
    print("\n"+"-"*50+"\n")

Column: age
readmitted         no        yes
age
[40-50)     55.489731  44.510269
[50-60)     55.840072  44.159928
[60-70)     53.154067  46.845933
[70-80)     51.206670  48.793330
[80-90)     50.420726  49.579274
[90-100)    57.866667  42.133333

--------------------------------------------------

Column: medical_specialty
readmitted                     no        yes
medical_specialty
Cardiology              55.003549  44.996451
Emergency/Trauma        50.610080  49.389920
Family/GeneralPractice  50.478215  49.521785
InternalMedicine        55.231417  44.768583
Missing                 51.090292  48.909708
Other                   58.521021  41.478979
Surgery                 58.779885  41.220115

--------------------------------------------------

Column: glucose_test
readmitted           no        yes
glucose_test
high          47.959184  52.040816
no            53.168254  46.831746
normal        51.669086  48.330914

--------------------------------------------------

Column: A1Ctest
readmitted         no        yes
A1Ctest
high        54.050230  45.949770
no          52.550387  47.449613
normal      57.894737  42.105263

--------------------------------------------------

Column: change
readmitted         no        yes
change
no          54.975180  45.024820
yes         50.647657  49.352343

--------------------------------------------------

Column: diabetes_med
readmitted           no        yes
diabetes_med
no            58.645184  41.354816
yes           51.284585  48.715415

--------------------------------------------------

In [13]:
# 1️⃣ Define numeric columns
numeric_cols = [
    'time_in_hospital',
    'n_lab_procedures',
    'n_procedures',
    'n_medications',
    'n_outpatient',
    'n_inpatient',
    'n_emergency'
]

# 2️⃣ Loop through each numeric column and calculate average per readmitted group
for col in numeric_cols:
    print(f"Column: {col}")
    print(df.groupby('readmitted')[col].mean())
    print("-"*50)

Column: time_in_hospital
readmitted
no     4.331345
yes    4.590778
Name: time_in_hospital, dtype: float64
--------------------------------------------------
Column: n_lab_procedures
readmitted
no     42.625245
yes    43.934405
Name: n_lab_procedures, dtype: float64
--------------------------------------------------
Column: n_procedures
readmitted
no     1.424204
yes    1.271397
Name: n_procedures, dtype: float64
--------------------------------------------------
Column: n_medications
readmitted
no     15.972445
yes    16.567892
Name: n_medications, dtype: float64
--------------------------------------------------
Column: n_outpatient
readmitted
no     0.258871
yes    0.487579
Name: n_outpatient, dtype: float64
--------------------------------------------------
Column: n_inpatient
readmitted
no     0.380190
yes    0.881657
Name: n_inpatient, dtype: float64
--------------------------------------------------
Column: n_emergency
readmitted
no     0.108561
yes    0.274545
Name: n_emergency, dtype: float64
--------------------------------------------------

In [14]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\ashna\appdata\roaming\python\python313\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sqlalchemy import create_engine

username = 'postgres'
password = 'Austintom123.'
host = 'localhost'
port = '5432'
database = 'care_home'

engine = create_engine(
    f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}'
)

table_name = "carehome"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")